'use strict';
const problems = [
 {title:'旅行準備サイト',context:'初めて海外旅行に行く人が、準備から帰国まで必要な情報を探すサイトを想定しています。',groups:[['渡航の準備','パスポート','ビザ','海外旅行保険','予防接種','緊急連絡先','渡航先の治安'],['移動・交通','航空券','空港アクセス','乗り継ぎ','鉄道パス','レンタカー','手荷物制限'],['宿泊','ホテル予約','チェックイン','チェックアウト','宿泊料金','客室設備','キャンセル規定'],['現地での過ごし方','観光スポット','レストラン','現地ツアー','美術館','お土産','イベント情報'],['お金・通信','両替','クレジットカード','海外SIM','Wi-Fi','ATM','通信料金']]},
 {title:'新入社員の社内ポータル',context:'新入社員が、毎日の仕事や社内手続きで迷わず情報を見つけるためのポータルです。',groups:[['働き方・勤怠','出勤打刻','休暇申請','残業申請','勤務時間','在宅勤務','遅刻連絡'],['お金・福利厚生','給与明細','交通費精算','健康診断','住宅補助','年末調整','社員割引'],['IT・ツール','パスワード変更','メール設定','VPN接続','PC貸出','ソフト申請','アカウント発行'],['人・組織','組織図','社員名簿','部署紹介','上司との面談','メンター制度','社内相談窓口'],['学び・ルール','新人研修','業務マニュアル','資格支援','情報セキュリティ','コンプライアンス','研修動画']]},
 {title:'暮らしの手続きガイド',context:'引っ越しや生活の変化に応じて、市民が必要な自治体の手続きを探す場面です。',groups:[['引っ越し・住まい','転入届','転出届','住所変更','住民票','水道開始','市営住宅'],['子育て','出生届','児童手当','保育園申込','母子手帳','乳幼児健診','子育て相談'],['健康・医療','国民健康保険','予防接種','がん検診','休日診療','医療費助成','健康相談'],['税・証明','住民税','納税証明','固定資産税','税金の相談','所得証明','納付方法'],['生活・環境','ごみ収集日','粗大ごみ','リサイクル','防災マップ','避難所','ペット登録']]}
];
const colors=['#57e3df','#b6a1ff','#ffc478','#78b9ff','#ff9cae'];
const $=id=>document.getElementById(id);
let problem,items=[],groups=[],selected=null,history=[],paused=matchMedia('(prefers-reduced-motion: reduce)').matches,submitted=false;
function shuffle(list){for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}return list;}
function start(){problem=problems[Number($('theme').value)];items=shuffle(problem.groups.flatMap((g,gi)=>g.slice(1,Number($('size').value)===15?4:7).map((text,i)=>({id:`${gi}-${i}`,text,reference:gi,group:null}))));groups=Array.from({length:3},(_,i)=>({id:i,label:''}));selected=null;history=[];submitted=false;$('result').hidden=true;$('topic').textContent=problem.title;render();}
function node(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function assign(id,target){if(submitted)return;const item=items.find(x=>x.id===id);if(!item||item.group===target)return;history.push({id,previous:item.group});item.group=target;selected=null;render();$('announcement').textContent=`${item.text}を${target===null?'未分類':(groups.find(g=>g.id===target).label||'箱'+(target+1))}へ移動しました`;}
function render(){
 $('cards').replaceChildren();items.filter(x=>x.group===null).forEach((item,i)=>{const b=node('button',item.text,'card'+(selected===item.id?' selected':''));b.style.setProperty('--delay',`${-i*.47}s`);b.dataset.item=item.id;b.disabled=submitted;b.setAttribute('aria-pressed',String(selected===item.id));b.addEventListener('click',()=>{selected=selected===item.id?null:item.id;render();});$('cards').append(b);});
 $('groups').replaceChildren();groups.forEach((g,i)=>{const box=node('section',undefined,'group');box.style.setProperty('--color',colors[i]);box.dataset.target=g.id;const top=node('div',undefined,'group-top');top.append(node('span',`BOX ${i+1}`));const input=node('input');input.placeholder='このグループの名前';input.maxLength=40;input.value=g.label;input.disabled=submitted;input.setAttribute('aria-label',`箱${i+1}のラベル`);input.addEventListener('input',()=>{g.label=input.value;update();});top.append(input);if(groups.length>3){const remove=node('button','×','remove');remove.setAttribute('aria-label',`箱${i+1}を削除してカードを戻す`);remove.disabled=submitted;remove.onclick=()=>{items.filter(x=>x.group===g.id).forEach(x=>x.group=null);groups=groups.filter(x=>x.id!==g.id);history=[];render();};top.append(remove);}box.append(top);const inv=node('div',undefined,'inventory');const contained=items.filter(x=>x.group===g.id);contained.forEach(item=>{const b=node('button',item.text+' ×');b.disabled=submitted;b.title='タップして未分類へ戻す';b.onclick=()=>assign(item.id,null);inv.append(b);});if(!contained.length)inv.append(node('p','ここにドロップ / 選んだカードをタップで入れる'));box.append(inv);box.addEventListener('click',e=>{if(selected&&!e.target.closest('input,button'))assign(selected,g.id);});$('groups').append(box);});
 update();
}
function update(){const remaining=items.filter(x=>x.group===null).length;const unlabeled=groups.filter(g=>!g.label.trim()).length;const empty=groups.filter(g=>!items.some(x=>x.group===g.id)).length;$('progress').textContent=`${items.length-remaining} / ${items.length} 枚 分類済み`;$('empty').hidden=remaining!==0;$('submit').disabled=submitted||remaining>0||unlabeled>0||empty>0;$('requirements').textContent=submitted?'提出済みです。新しく始めると、もう一度練習できます。':remaining?`残り${remaining}枚。すべて分類して、各箱にラベルを付けよう。`:unlabeled?`名前のない箱が${unlabeled}個あります。`:empty?'空の箱を使うか、削除してください。':'準備完了。あなたの分類を模範例と比べてみよう。';$('add').disabled=groups.length>=5||submitted;$('undo').disabled=!history.length||submitted;$('selection').textContent=selected?`「${items.find(x=>x.id===selected).text}」を選択中 → 箱をタップ`:'カードを選んで分類しよう';document.body.classList.toggle('paused',paused);$('motion').textContent=paused?'浮遊を再開':'浮遊を止める';$('motion').setAttribute('aria-pressed',String(paused));}
// Pairwise F1 compares memberships without depending on container order or names.
function score(list){let tp=0,fp=0,fn=0;for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const expected=list[i].reference===list[j].reference;const actual=list[i].group===list[j].group;if(expected&&actual)tp++;else if(actual)fp++;else if(expected)fn++;}return Math.round(100*(2*tp)/(2*tp+fp+fn||1));}
function submit(){if($('submit').disabled)return;submitted=true;selected=null;render();const out=$('result');out.replaceChildren();out.append(node('p','03 / REFLECTION','eyebrow'),node('h2',`模範例との分類の近さ ${score(items)} / 100`),node('p',problem.context),node('p','同じ箱に入れたカードの組み合わせを模範例と比較しています。ラベル名は採点していません。異なる切り口の分類にも価値があります。'));const columns=node('div',undefined,'comparison');const own=node('div');own.append(node('h3','あなたの分類'));const ref=node('div');ref.append(node('h3','模範例'));function block(parent,label,texts){const b=node('div',undefined,'result-group');b.append(node('h4',label),node('p',texts.join(' ・ ')));parent.append(b);}groups.forEach(g=>block(own,g.label,items.filter(x=>x.group===g.id).map(x=>x.text)));problem.groups.forEach((g,i)=>block(ref,g[0],items.filter(x=>x.reference===i).map(x=>x.text)));columns.append(own,ref);out.append(columns,node('p','振り返りのヒント：箱の中のキーワードを、ラベルだけで予測できるでしょうか？ 同じ粒度で名前を付けられているでしょうか？'));const next=node('button','次のテーマで練習する →');next.onclick=()=>{$('theme').value=(Number($('theme').value)+1)%problems.length;start();$('topic').scrollIntoView({behavior:'smooth'});};out.append(next);out.hidden=false;out.scrollIntoView({behavior:'smooth',block:'start'});}
$('size').replaceChildren();[['15','15枚 · はじめて'],['30','30枚 · じっくり']].forEach(([value,label])=>{const option=node('option',label);option.value=value;$('size').append(option);});$('size').value='30';
let drag=null;
document.addEventListener('pointerdown',e=>{const card=e.target.closest('.card');if(!card||submitted)return;drag={id:card.dataset.item,x:e.clientX,y:e.clientY,ghost:null};card.setPointerCapture(e.pointerId);});
document.addEventListener('pointermove',e=>{if(!drag)return;if(!drag.ghost&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8){drag.ghost=node('div',items.find(x=>x.id===drag.id).text,'ghost');document.body.append(drag.ghost);}if(drag.ghost){drag.ghost.style.left=e.clientX+'px';drag.ghost.style.top=e.clientY+'px';const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.group');document.querySelectorAll('.group').forEach(g=>g.classList.toggle('over',g===target));}});
function cancelDrag(){drag?.ghost?.remove();drag=null;document.querySelectorAll('.over').forEach(g=>g.classList.remove('over'));}
document.addEventListener('pointerup',e=>{if(!drag)return;if(drag.ghost){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.group');const id=drag.id;cancelDrag();if(target)assign(id,Number(target.dataset.target));const suppress=event=>{event.stopPropagation();event.preventDefault();};document.addEventListener('click',suppress,{capture:true,once:true});setTimeout(()=>document.removeEventListener('click',suppress,true),0);}else cancelDrag();});document.addEventListener('pointercancel',cancelDrag);
problems.forEach((p,i)=>{const option=node('option',p.title);option.value=i;$('theme').append(option);});$('restart').onclick=start;$('theme').onchange=start;$('size').onchange=start;$('add').onclick=()=>{groups.push({id:Math.max(...groups.map(g=>g.id))+1,label:''});render();};$('undo').onclick=()=>{const last=history.pop();if(last){items.find(x=>x.id===last.id).group=last.previous;selected=null;render();}};$('motion').onclick=()=>{paused=!paused;update();};$('submit').onclick=submit;start();
// WebGL atmosphere is optional; sorting stays available if the CDN or GPU is unavailable.
(async()=>{try{const THREE=await import('https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js');const host=$('scene'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(45,1,.1,100);camera.position.set(0,4,12);camera.lookAt(0,0,0);const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.append(renderer.domElement);const grid=new THREE.GridHelper(35,35,0x326887,0x17374b);grid.position.y=-3;scene.add(grid);const geometry=new THREE.IcosahedronGeometry(.5,0);const shapes=Array.from({length:16},(_,i)=>{const mesh=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({color:i%2?0x57e3df:0x8792d8,wireframe:true,transparent:true,opacity:.12}));mesh.position.set((Math.random()-.5)*18,(Math.random()-.5)*8,-Math.random()*7);scene.add(mesh);return mesh;});new ResizeObserver(()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();}).observe(host);renderer.setAnimationLoop(()=>{if(!paused)shapes.forEach(m=>{m.rotation.x+=.001;m.rotation.y+=.002;});renderer.render(scene,camera);});$('render-mode').textContent='THREE.JS / 3D SPACE';}catch(e){$('render-mode').textContent='2Dフロート表示';}})();
